# Generated by Django 4.2.28 on 2026-02-20 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(help_text='Maritime Mobile Service Identity', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('ship_type', models.CharField(choices=[('cargo', 'Cargo'), ('tanker', 'Tanker'), ('passenger', 'Passenger/Ferry'), ('tug', 'Tugboat'), ('fishing', 'Fishing'), ('military', 'Military'), ('pleasure', 'Pleasure Craft'), ('other', 'Other')], default='other', max_length=20)),
                ('weight_tonnage', models.FloatField(default=0, help_text='Gross tonnage')),
                ('flag', models.CharField(blank=True, default='', max_length=100)),
                ('length', models.FloatField(default=0, help_text='Length in meters')),
                ('width', models.FloatField(default=0, help_text='Width/beam in meters')),
                ('destination', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('polygon_json', models.TextField(help_text='GeoJSON polygon coordinates')),
                ('color', models.CharField(default='#ff9500', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('enter', 'Entered Zone'), ('exit', 'Exited Zone')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vessels.vessel')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vessels.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DroneSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('current_latitude', models.FloatField()),
                ('current_longitude', models.FloatField()),
                ('target_latitude', models.FloatField()),
                ('target_longitude', models.FloatField()),
                ('status', models.CharField(choices=[('deploying', 'Deploying'), ('in_transit', 'In Transit'), ('observing', 'Observing'), ('returning', 'Returning'), ('completed', 'Completed')], default='deploying', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_missions', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0, help_text='Speed in knots')),
                ('heading', models.FloatField(default=0, help_text='Heading in degrees')),
                ('course', models.FloatField(default=0, help_text='Course over ground in degrees')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vessel', '-timestamp'], name='vessels_ves_vessel__2ffb7b_idx')],
            },
        ),
    ]
